### PR TITLE
Update Rust to `nightly-2024-01-05`

### PR DESCRIPTION
**Pull request by koute**
This PR updates Rust to the most current (as of today) `nightly-2024-01-05` and also adds two new targets:

* `riscv32ema-unknown-none-elf`
* `riscv64ema-unknown-none-elf`

The 64-bit target is completely untested, but I've added it anyway so that it's ready once I start implementing 64-bit support in PolkaVM, and the new 32-bit target is for when I'll finish adding support for the A extension to the linker (which should be soon), which will be the new default target triplet (mostly for compatibility, because a lot of 3rd party crates assume `core::sync::atomic::*` stuff exists, and I don't want to patch the world nor special-case Rust's standard library just for our special snowflake use case).

The RV32E patch was also updated to the newest version.

### CODE REVIEW

**Comment by athei** [comment]
Thanks. Since we have no CI in the PR anymore. I will try to build on my M1. I assume you tested in your linux machine.

**Comment by koute** [comment]
Yes, it works on my machine. (Although I haven't done a clean bootstrap purely using the scripts; I was manually building it until I managed to get everything to compile correctly. But it's probably fine.)

**Comment by athei** [comment]
Builds on my machine using the scripts. Please bump the number in version.txt so a new release will be drafted after merging.

**Comment by koute** [comment]
Done.

**Comment by pgherveou** [comment]
nice let's merge it so we can use the new toolchain, we can always amend in follow up PR if needed

**Pull request merged**
